// Include lib .c files directly
#include "lib/string.c"
#include "lib/common.c"
#include "lib/memory.c"
#include "lib/string_builder.c"
#include "lib/thread_context.h"
#include "os/os.h"
#include "os/os_wasm.c"
#include "lib/thread.c"
#include "lib/thread_context.c"
#include "lib/multicore_runtime.c"
#include "gpu.c"
#include "renderer.c"
#include "lib/handle.c"
#include "lib/math.h"
#include "cube.h"
#include "renderer.h"
#include "input.h"
#include "camera.h"
#include "camera.c"
#include "context.c"
#include "entrypoint.c"
// #include "demos/demo_cube_instancing.c"
// #include "demos/demo_hello_world.c"
// #include "demos/demo_multicore_tasks.c"
// #include "demos/demo_ecs.c"
// #include "demos/demo_ecs_components.c"
// #include "demos/demo_ecs_tables.c"
// #include "demos/demo_ecs_add_remove.c"
// #include "demos/demo_ecs_query.c"
// #include "demos/demo_ecs_query_cache.c"
// #include "demos/demo_ecs_inout.c"
// #include "demos/demo_ecs_change_detection.c"
#include "demos/demo_ecs_systems.c"
