[package]
name = "wolfestein-engine-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.1"
sdl2 = { version = "0.35.2", features = ["bundled", "unsafe_textures"] }
