[package]
name = "rust_wasm_basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[dependencies]
wasm-bindgen = "0.2.92"
