
#include "src/video_renderer.c"
#include "os/os.c"
#include "lib/string_builder.c"
#include "lib/string.c"
#include "lib/json_parser.c"
#include "lib/profiler.c"
#include "lib/handle.c"
#include "lib/common.c"
#include "src/game.c"
#include "src/gpu_backend_vulkan.c"
#include "src/renderer/renderer.c"
