#include "src/lib.c"
#include "src/main.c"
#include "src/vendor.c"
#include "src/wgpuex.c"
#include "src/lib/string.c"
#include "src/pipelines/default2d.c"
#include "src/renderers/renderer_basic2d.c"
