#include "os/os.c"
#include "lib/common.c"
#include "lib/string.c"
#include "lib/memory.c"
#include "lib/pthread_barrier.c"
#include "lib/thread_context.c"
// #include "multicore_homogeneous.c"
#include "multicore_tasks.c"
