#include "lib/common.c"
#include "lib/string.c"
#include "lib/string_builder.c"
#include "lib/memory.c"
#include "lib/thread.c"
#include "lib/thread_context.h"
#include "lib/thread_context.c"
#include "lib/task.c"
#include "os/os.c"
// #include "multicore_homogeneous.c"
#include "multicore_tasks.c"
